//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiClient.AdvertiserService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="NameCollection", Namespace="http://www.adform.com/api/2010/06", ItemName="Name")]
    [System.SerializableAttribute()]
    public class NameCollection : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Advertiser", Namespace="http://www.adform.com/api/2010/06")]
    [System.SerializableAttribute()]
    public partial class Advertiser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgencyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int AgencyId {
            get {
                return this.AgencyIdField;
            }
            set {
                if ((this.AgencyIdField.Equals(value) != true)) {
                    this.AgencyIdField = value;
                    this.RaisePropertyChanged("AgencyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAdvertisersData", Namespace="http://www.adform.com/api/2010/06")]
    [System.SerializableAttribute()]
    public partial class GetAdvertisersData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApiClient.AdvertiserService.NameCollection NamesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApiClient.AdvertiserService.NameCollection Names {
            get {
                return this.NamesField;
            }
            set {
                if ((object.ReferenceEquals(this.NamesField, value) != true)) {
                    this.NamesField = value;
                    this.RaisePropertyChanged("Names");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.adform.com/api/2010/06", ConfigurationName="AdvertiserService.IAdvertiserService")]
    public interface IAdvertiserService {
        
        // CODEGEN: Generating message contract since the operation GetAdvertisers is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adform.com/api/2010/06/IAdvertiserService/GetAdvertisers", ReplyAction="http://www.adform.com/api/2010/06/IAdvertiserService/GetAdvertisersResponse")]
        ApiClient.AdvertiserService.GetAdvertisersResponse GetAdvertisers(ApiClient.AdvertiserService.GetAdvertisersData1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adform.com/api/2010/06/IAdvertiserService/GetAdvertisers", ReplyAction="http://www.adform.com/api/2010/06/IAdvertiserService/GetAdvertisersResponse")]
        System.Threading.Tasks.Task<ApiClient.AdvertiserService.GetAdvertisersResponse> GetAdvertisersAsync(ApiClient.AdvertiserService.GetAdvertisersData1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAdvertisersData1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.adform.com/api/2010/06")]
        public string Ticket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adform.com/api/2010/06", Order=0)]
        public ApiClient.AdvertiserService.GetAdvertisersData GetAdvertisersData;
        
        public GetAdvertisersData1() {
        }
        
        public GetAdvertisersData1(string Ticket, ApiClient.AdvertiserService.GetAdvertisersData GetAdvertisersData) {
            this.Ticket = Ticket;
            this.GetAdvertisersData = GetAdvertisersData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAdvertisersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adform.com/api/2010/06", Order=0)]
        public ApiClient.AdvertiserService.Advertiser[] Advertisers;
        
        public GetAdvertisersResponse() {
        }
        
        public GetAdvertisersResponse(ApiClient.AdvertiserService.Advertiser[] Advertisers) {
            this.Advertisers = Advertisers;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdvertiserServiceChannel : ApiClient.AdvertiserService.IAdvertiserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdvertiserServiceClient : System.ServiceModel.ClientBase<ApiClient.AdvertiserService.IAdvertiserService>, ApiClient.AdvertiserService.IAdvertiserService {
        
        public AdvertiserServiceClient() {
        }
        
        public AdvertiserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdvertiserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdvertiserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdvertiserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiClient.AdvertiserService.GetAdvertisersResponse ApiClient.AdvertiserService.IAdvertiserService.GetAdvertisers(ApiClient.AdvertiserService.GetAdvertisersData1 request) {
            return base.Channel.GetAdvertisers(request);
        }
        
        public ApiClient.AdvertiserService.Advertiser[] GetAdvertisers(string Ticket, ApiClient.AdvertiserService.GetAdvertisersData GetAdvertisersData) {
            ApiClient.AdvertiserService.GetAdvertisersData1 inValue = new ApiClient.AdvertiserService.GetAdvertisersData1();
            inValue.Ticket = Ticket;
            inValue.GetAdvertisersData = GetAdvertisersData;
            ApiClient.AdvertiserService.GetAdvertisersResponse retVal = ((ApiClient.AdvertiserService.IAdvertiserService)(this)).GetAdvertisers(inValue);
            return retVal.Advertisers;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApiClient.AdvertiserService.GetAdvertisersResponse> ApiClient.AdvertiserService.IAdvertiserService.GetAdvertisersAsync(ApiClient.AdvertiserService.GetAdvertisersData1 request) {
            return base.Channel.GetAdvertisersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApiClient.AdvertiserService.GetAdvertisersResponse> GetAdvertisersAsync(string Ticket, ApiClient.AdvertiserService.GetAdvertisersData GetAdvertisersData) {
            ApiClient.AdvertiserService.GetAdvertisersData1 inValue = new ApiClient.AdvertiserService.GetAdvertisersData1();
            inValue.Ticket = Ticket;
            inValue.GetAdvertisersData = GetAdvertisersData;
            return ((ApiClient.AdvertiserService.IAdvertiserService)(this)).GetAdvertisersAsync(inValue);
        }
    }
}
